<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <AssemblyName>Online.Shared</AssemblyName>
        <RootNamespace>Stilbite.Online.Shared</RootNamespace>
    </PropertyGroup>

    <Target Name="CopyDllAfterBuild" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)..\Stilbite\Assets\Plugins\" />
    </Target>

</Project>